library(dplyr)
mechcar <- read.csv(file= "MechaCar_mpg.csv")
car <- lm(mpg ~ vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD, data=mechcar)
summary(car)
suspensioncoil <- read.csv(file = "Suspension_Coil.csv")
total_summary <- suspensioncoil %>% summarize (Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI), .groups = "keep")
lot_summary <- suspensioncoil %>% group_by (Manufacturing_Lot) %>% summarize (Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI), .groups = "keep")
t.test(suspensioncoil $PSI, mu = 1500)
t.test(subset(suspensioncoil, Manufacturing_Lot="Lot1") $PSI, mu = 1500)
t.test(subset(suspensioncoil, Manufacturing_Lot="Lot2") $PSI, mu = 1500)
t.test(subset(suspensioncoil, Manufacturing_Lot="Lot3") $PSI, mu = 1500)
